url: https://rrfi.github.io
baseurl:
destination: _site

# Site settings
title: Recumbent Racing Finland
email: pekka.heimonen@gmail.com
description: "We ride recumbents but we love cycling and all kind of bikes. Every August we organise an open Finnish Recumbent Championship race in Nokia, Finland."


# Team names, titles and social links
people:
- name: Teppo Mäkelä
  pic: 1
  position-fi: Nokian kilpailujen isä. Tapahtuman johtaja, ratamestari. Teppo hoitaa.
  position-en: Mastermind of the event. Race commander, track maister. Teppo takes care of everything.
  social:

- name: Tero Linnanen
  pic: 2
  position-fi: Hallituksen puheenjohtaja. Kansainväliset kisat kolunnut kisakonkari ja hiilikuiturakentaja.
  position-en: Chairman of the board. Regular competitor in international races. Carbon fiber specialist. 
  social:

- name: Pasi Räsämäki
  pic: 3
  position-fi: HC nojapyöräilijä Joensuusta.
  position-en: HC recumbent rider and builder from the North Karelian town of Joensuu.
  social:

- name: Sauli Nurila
  pic: 5
  position-fi: Kinneristi Kälviän tasangoilta. Ansioitunut someaktivisti.
  position-en: Velomobile rider from the western flatlands. Reputed social media activist.
  social:
    - title: twitter
      url: https://twitter.com/saukkico
    - title: facebook
      url: https://www.facebook.com/saukkico
    - title: youtube
      url: https://www.youtube.com/user/saukki86
    - title: instagram
      url: https://www.instagram.com/saukkico
 
- name: Henri Heikkari
  pic: 6
  position-fi: Kemppi-tyylin virittäjä Suomen Mansesterista.
  position-en: >
     "Fine-tuning by welding" specialist from Manchester Finland.
  social:

- name: Pekka Heimonen
  pic: 4
  position-fi: Suomen nojapyöräilyn lahja Ranskalle. Webmaster. 
  position-en: The French connection. Webmaster. 
  social:
    - title: twitter
      url: https://twitter.com/pekkaheimonen
    - title: bicycle
      url: https://www.strava.com/athletes/2250684
    - title: link
      url: http://teamheimonen.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Recumbent-Racing-Finland-ry-415378888637978

# Postal address (add as many lines as necessary)
address:
  - line: Nokia
  - line: Finland

# Build settings
markdown: kramdown
permalink: pretty