url: https://rrfi.github.io
baseurl:
destination: _site

# Site settings
title: Recumbent Racing Finland
email: pekka.heimonen@gmail.com
description: "We ride recumbents but we love cycling and all kind of bikes. Every August we organise an open Finnish Recumbent Championship race in Nokia, Finland."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Recumbent-Racing-Finland-ry-415378888637978

# Postal address (add as many lines as necessary)
address:
  - line: Nokia
  - line: Finland

# Gallery static file defaults
defaults:
  - 
    scope:
      path: "photos"
    values:
      image: true

# Build settings
markdown: kramdown

permalink: pretty